### ISSUE TITLE
Can't import ics under 32-bit python environment

### ISSUE THREAD

**Issue by dong408765778** [intrepidcs/python_ics#109]
Environment:
1. Win10
2. 32-bit python
3. spy3.8.2.111 installed

When I try to import ics under 32-bit python environment, I got an error
```
D:\AutoStudio\superman\202108051007_95\thundersoftautostudio\Python32>python.exe
Python 3.8.7 (tags/v3.8.7:6503f05, Dec 21 2020, 17:43:54) [MSC v.1928 32 bit (Intel)]
 on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import ics
Traceback (most recent call last):
  File "D:\AutoStudio\superman\202108051007_95\thundersoftautostudio\Python32\lib\sit
e-packages\python_ics-903.17-py3.8-win32.egg\ics\__init__.py", line 3, in <module>
    from structures import *
ModuleNotFoundError: No module named 'structures'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\AutoStudio\superman\202108051007_95\thundersoftautostudio\Python32\lib\sit
e-packages\python_ics-903.17-py3.8-win32.egg\ics\__init__.py", line 5, in <module>
    from ics.ics import *
ImportError: DLL load failed while importing ics: 找不到指定的模块。
>>>
```

**Comment by ic3man5** [comment]
903.17 is old, please update to latest 905.11.

`pip install python_ics --upgrade`

**Comment by ic3man5** [comment]
#99

**Comment by dong408765778** [comment]
> 903.17 is old, please update to latest 905.11.
> 
> `pip install python_ics --upgrade`

Got same error with 905.11
```
D:\AutoStudio\superman\202108051007_95\thundersoftautostudio\Python32>python.exe
Python 3.8.7 (tags/v3.8.7:6503f05, Dec 21 2020, 17:43:54) [MSC v.1928 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import ics
DLL load failed while importing ics: 找不到指定的模块。
Traceback (most recent call last):
  File "D:\AutoStudio\superman\202108051007_95\thundersoftautostudio\Python32\lib\site-packages\ics\__init__.py", line 6, in <module>
    from ics.ics import *
ImportError: DLL load failed while importing ics: 找不到指定的模块。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\AutoStudio\superman\202108051007_95\thundersoftautostudio\Python32\lib\site-packages\ics\__init__.py", line 11, in <module>
    from ics.ics import *
ImportError: DLL load failed while importing ics: 找不到指定的模块。
```

**Comment by drebbe-intrepid** [comment]
```ImportError: DLL load failed while importing ics: 找不到指定的模块。```

This is related to not being able to load the `icsneo40.dll` properly. Google translate says "The specified module could not be found.". This means icsneo40.dll is not in your system path.

**Comment by drebbe-intrepid** [comment]
I'm closing this out; if you are still having issues, feel free to re-open this.
