### ISSUE TITLE
How to build a app(*.exe)?

### ISSUE THREAD

**Issue by YongwangWu** [intrepidcs/python_ics#120]
I tried to build a application,for example,to build a module in examples folder with pyinstaller,it output a transmit_can_example.exe,however,it raise error.
The detail is as following:

PS E:\Programs\Pythons\Trial\python_ics-master\examples\dist> .\transmit_can_example.exe
Traceback (most recent call last):
  File "transmit_can_example.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "ics\__init__.py", line 2, in <module>

**Comment by YongwangWu** [comment]
Traceback (most recent call last):
  File "transmit_can_example.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "ics\__init__.py", line 2, in <module>
AttributeError: module 'ics.structures' has no attribute 's_extended_data_flash_header'
[19980] Failed to execute script 'transmit_can_example' due to unhandled exception!

**Comment by drebbe-intrepid** [comment]
Please see https://python-ics.readthedocs.io/en/v905.10/#pyinstaller for details on how to use PyInstaller with this module

**Comment by drebbe-intrepid** [comment]
I'm going to close this out assuming this issue has been resolved. Please feel free to re-open this if not.
