### ISSUE TITLE
After I package the exe, the program will report an error

### ISSUE THREAD

**Issue by hjkipom** [intrepidcs/python_ics#121]
error code:
File "ics\__init__.py", line 2, in <module>
AttributeError: module  'ics.structures' has no attribute 's_extended_data_flash_header'

**Comment by hjkipom** [comment]
The whole process

Traceback (most recent call last):
  File "GUI.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "C:\Users\Lenovo\AppData\Roaming\Python\Python39\site-packages\PyInstaller\loader\pyimod03_importers.py", line 49
3, in exec_module
    exec(bytecode, module.__dict__)
  File "MODEL.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "C:\Users\Lenovo\AppData\Roaming\Python\Python39\site-packages\PyInstaller\loader\pyimod03_importers.py", line 49
3, in exec_module
    exec(bytecode, module.__dict__)
  File "VALUE_CAN4.py", line 555, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "C:\Users\Lenovo\AppData\Roaming\Python\Python39\site-packages\PyInstaller\loader\pyimod03_importers.py", line 49
3, in exec_module
    exec(bytecode, module.__dict__)
  File "ics\__init__.py", line 2, in <module>
AttributeError: module 'ics.structures' has no attribute 's_extended_data_flash_header'

**Comment by drebbe-intrepid** [comment]
Please see https://python-ics.readthedocs.io/en/v905.10/#pyinstaller for details on how to package

**Comment by drebbe-intrepid** [comment]
I'm going to close this out assuming this issue has been resolved. Please feel free to re-open this if not.
