### ISSUE TITLE
Migrate to new build module

### ISSUE THREAD

**Issue by drebbe-intrepid** [intrepidcs/python_ics#183]
We can't currently build with https://pypi.org/project/build/ module as it creates a build environment that strips git repository information. `--no-isolation` flag doesn't seem to make a difference.

```RuntimeError: This does not appear to be a Git project```

```python
Creating 'gen/ics/__init__.py'...
Traceback (most recent call last):
  File "/home/drebbe/dev/python_ics/.venv/lib/python3.12/site-packages/pyproject_hooks/_in_process/_in_process.py", line 373, in <module>
    main()
  File "/home/drebbe/dev/python_ics/.venv/lib/python3.12/site-packages/pyproject_hooks/_in_process/_in_process.py", line 357, in main
    json_out["return_val"] = hook(**hook_input["kwargs"])
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/drebbe/dev/python_ics/.venv/lib/python3.12/site-packages/pyproject_hooks/_in_process/_in_process.py", line 134, in get_requires_for_build_wheel
    return hook(config_settings)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/drebbe/dev/python_ics/.venv/lib/python3.12/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
    return self._get_build_requires(config_settings, requirements=['wheel'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/drebbe/dev/python_ics/.venv/lib/python3.12/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
    self.run_setup()
  File "/home/drebbe/dev/python_ics/.venv/lib/python3.12/site-packages/setuptools/build_meta.py", line 487, in run_setup
    super().run_setup(setup_script=setup_script)
  File "/home/drebbe/dev/python_ics/.venv/lib/python3.12/site-packages/setuptools/build_meta.py", line 311, in run_setup
    exec(code, locals())
  File "<string>", line 19, in <module>
  File "/tmp/build-via-sdist-lbdn3301/ics-908.0/ics_utility.py", line 33, in create_version_py
    pkg_version = get_pkg_version()
                  ^^^^^^^^^^^^^^^^^
  File "/tmp/build-via-sdist-lbdn3301/ics-908.0/ics_utility.py", line 15, in get_pkg_version
    version = dunamai.Version.from_git()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/drebbe/dev/python_ics/.venv/lib/python3.12/site-packages/dunamai/__init__.py", line 1121, in from_git
    _detect_vcs(vcs, path)
  File "/home/drebbe/dev/python_ics/.venv/lib/python3.12/site-packages/dunamai/__init__.py", line 378, in _detect_vcs
    raise RuntimeError(
RuntimeError: This does not appear to be a Git project

ERROR Backend subprocess exited when trying to invoke get_requires_for_build_wheel
```

**Comment by drebbe-intrepid** [comment]
@pierreluctg FYI

**Comment by drebbe-intrepid** [comment]
documentation conf.py still is hard coded, need to update this also.

**Comment by drebbe-intrepid** [comment]
workflow doesn't trigger when tag is pushed after commit / MR is merged.
