### ISSUE TITLE
Segmentation Fault running tests on Fedora Linux

### ISSUE THREAD

**Issue by cottsay** [intrepidcs/python_ics#24]
This occurs when running `python setup.py test` with both python 2 and 3. Here is the backtrace coming out of `gdb -batch -ex run -ex bt --args python3 test/test_find_devices.py`:

```c++
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
arg_parse (args=args@entry=0x7fffe9a7344d "s:", func=func@entry=0x7fffe9a74c80 <meth_override_library_name(_object*, _object*)::__FUNCTION__> "meth_override_library_name") at src/methods.cpp:47
47	    memset(buffer, '\0', sizeof(buffer)/sizeof(buffer[0]));
#0  arg_parse (args=args@entry=0x7fffe9a7344d "s:", func=func@entry=0x7fffe9a74c80 <meth_override_library_name(_object*, _object*)::__FUNCTION__> "meth_override_library_name") at src/methods.cpp:47
#1  0x00007fffe9a4b43e in meth_override_library_name(_object*, _object*) () at src/methods.cpp:4095
#2  0x00007ffff79ed942 in _PyCFunction_FastCallDict () at /usr/src/debug/python3-3.6.6-1.fc28.x86_64/Objects/methodobject.c:234
#3  0x00007ffff79edc9a in _PyCFunction_FastCallKeywords () at /usr/src/debug/python3-3.6.6-1.fc28.x86_64/Objects/methodobject.c:275
#4  0x00007ffff79fcbdd in call_function () at /usr/src/debug/python3-3.6.6-1.fc28.x86_64/Python/ceval.c:4830
#5  0x00007ffff7a2d12a in _PyEval_EvalFrameDefault () at /usr/src/debug/python3-3.6.6-1.fc28.x86_64/Python/ceval.c:3328
#6  0x00007ffff79b4d5a in _PyFunction_FastCall (globals=<optimized out>, nargs=1, args=<optimized out>, co=<optimized out>) at /usr/src/debug/python3-3.6.6-1.fc28.x86_64/Python/ceval.c:4947
#7  fast_function () at /usr/src/debug/python3-3.6.6-1.fc28.x86_64/Python/ceval.c:4947
#8  0x00007ffff79fccc2 in call_function () at /usr/src/debug/python3-3.6.6-1.fc28.x86_64/Python/ceval.c:4851
#9  0x00007ffff7a2d12a in _PyEval_EvalFrameDefault () at /usr/src/debug/python3-3.6.6-1.fc28.x86_64/Python/ceval.c:3328
#10 0x00007ffff79b4d5a in _PyFunction_FastCall (globals=<optimized out>, nargs=3, args=<optimized out>, co=<optimized out>) at /usr/src/debug/python3-3.6.6-1.fc28.x86_64/Python/ceval.c:4947
#11 fast_function () at /usr/src/debug/python3-3.6.6-1.fc28.x86_64/Python/ceval.c:4947
#12 0x00007ffff79fccc2 in call_function () at /usr/src/debug/python3-3.6.6-1.fc28.x86_64/Python/ceval.c:4851
#13 0x00007ffff7a2d12a in _PyEval_EvalFrameDefault () at /usr/src/debug/python3-3.6.6-1.fc28.x86_64/Python/ceval.c:3328
#14 0x00007ffff797e02b in _PyEval_EvalCodeWithName () at /usr/src/debug/python3-3.6.6-1.fc28.x86_64/Python/ceval.c:4159
#15 0x00007ffff797f50d in _PyFunction_FastCallDict () at /usr/src/debug/python3-3.6.6-1.fc28.x86_64/Python/ceval.c:5063
#16 0x00007ffff797faae in _PyObject_FastCallDict () at /usr/src/debug/python3-3.6.6-1.fc28.x86_64/Objects/abstract.c:2310
#17 0x00007ffff798b3f0 in _PyObject_Call_Prepend () at /usr/src/debug/python3-3.6.6-1.fc28.x86_64/Objects/abstract.c:2373
#18 0x00007ffff797fe83 in PyObject_Call () at /usr/src/debug/python3-3.6.6-1.fc28.x86_64/Objects/abstract.c:2261
#19 0x00007ffff7a2eb80 in do_call_core (kwdict=<unknown at remote 0x7fffe9202480>, callargs=<unknown at remote 0x7fffe9ed3d68>, func=<unknown at remote 0x7ffff7ec8608>) at /usr/src/debug/python3-3.6.6-1.fc28.x86_64/Python/ceval.c:5099
#20 _PyEval_EvalFrameDefault () at /usr/src/debug/python3-3.6.6-1.fc28.x86_64/Python/ceval.c:3397
#21 0x00007ffff797e02b in _PyEval_EvalCodeWithName () at /usr/src/debug/python3-3.6.6-1.fc28.x86_64/Python/ceval.c:4159
#22 0x00007ffff797f2e8 in _PyFunction_FastCallDict () at /usr/src/debug/python3-3.6.6-1.fc28.x86_64/Python/ceval.c:5054
#23 0x00007ffff797faae in _PyObject_FastCallDict () at /usr/src/debug/python3-3.6.6-1.fc28.x86_64/Objects/abstract.c:2310
#24 0x00007ffff798b3f0 in _PyObject_Call_Prepend () at /usr/src/debug/python3-3.6.6-1.fc28.x86_64/Objects/abstract.c:2373
#25 0x00007ffff797fe83 in PyObject_Call () at /usr/src/debug/python3-3.6.6-1.fc28.x86_64/Objects/abstract.c:2261
#26 0x00007ffff79f3b65 in slot_tp_call () at /usr/src/debug/python3-3.6.6-1.fc28.x86_64/Objects/typeobject.c:6194
#27 0x00007ffff797f81b in _PyObject_FastCallDict () at /usr/src/debug/python3-3.6.6-1.fc28.x86_64/Objects/abstract.c:2331
#28 0x00007ffff79edd38 in _PyObject_FastCallKeywords () at /usr/src/debug/python3-3.6.6-1.fc28.x86_64/Objects/abstract.c:2482
#29 0x00007ffff79fcd41 in call_function () at /usr/src/debug/python3-3.6.6-1.fc28.x86_64/Python/ceval.c:4854
#30 0x00007ffff7a2d12a in _PyEval_EvalFrameDefault () at /usr/src/debug/python3-3.6.6-1.fc28.x86_64/Python/ceval.c:3328
#31 0x00007ffff797e02b in _PyEval_EvalCodeWithName () at /usr/src/debug/python3-3.6.6-1.fc28.x86_64/Python/ceval.c:4159
#32 0x00007ffff797f50d in _PyFunction_FastCallDict () at /usr/src/debug/python3-3.6.6-1.fc28.x86_64/Python/ceval.c:5063
#33 0x00007ffff797faae in _PyObject_FastCallDict () at /usr/src/debug/python3-3.6.6-1.fc28.x86_64/Objects/abstract.c:2310
#34 0x00007ffff798b3f0 in _PyObject_Call_Prepend () at /usr/src/debug/python3-3.6.6-1.fc28.x86_64/Objects/abstract.c:2373
#35 0x00007ffff797fe83 in PyObject_Call () at /usr/src/debug/python3-3.6.6-1.fc28.x86_64/Objects/abstract.c:2261
#36 0x00007ffff7a2eb80 in do_call_core (kwdict=<unknown at remote 0x7fffe9202630>, callargs=<unknown at remote 0x7fffe9ed3be0>, func=<unknown at remote 0x7fffea329f88>) at /usr/src/debug/python3-3.6.6-1.fc28.x86_64/Python/ceval.c:5099
#37 _PyEval_EvalFrameDefault () at /usr/src/debug/python3-3.6.6-1.fc28.x86_64/Python/ceval.c:3397
#38 0x00007ffff797e02b in _PyEval_EvalCodeWithName () at /usr/src/debug/python3-3.6.6-1.fc28.x86_64/Python/ceval.c:4159
#39 0x00007ffff797f2e8 in _PyFunction_FastCallDict () at /usr/src/debug/python3-3.6.6-1.fc28.x86_64/Python/ceval.c:5054
#40 0x00007ffff797faae in _PyObject_FastCallDict () at /usr/src/debug/python3-3.6.6-1.fc28.x86_64/Objects/abstract.c:2310
#41 0x00007ffff798b3f0 in _PyObject_Call_Prepend () at /usr/src/debug/python3-3.6.6-1.fc28.x86_64/Objects/abstract.c:2373
#42 0x00007ffff797fe83 in PyObject_Call () at /usr/src/debug/python3-3.6.6-1.fc28.x86_64/Objects/abstract.c:2261
#43 0x00007ffff79f3b65 in slot_tp_call () at /usr/src/debug/python3-3.6.6-1.fc28.x86_64/Objects/typeobject.c:6194
#44 0x00007ffff797f81b in _PyObject_FastCallDict () at /usr/src/debug/python3-3.6.6-1.fc28.x86_64/Objects/abstract.c:2331
#45 0x00007ffff79edd38 in _PyObject_FastCallKeywords () at /usr/src/debug/python3-3.6.6-1.fc28.x86_64/Objects/abstract.c:2482
#46 0x00007ffff79fcd41 in call_function () at /usr/src/debug/python3-3.6.6-1.fc28.x86_64/Python/ceval.c:4854
#47 0x00007ffff7a2d12a in _PyEval_EvalFrameDefault () at /usr/src/debug/python3-3.6.6-1.fc28.x86_64/Python/ceval.c:3328
#48 0x00007ffff79b4d5a in _PyFunction_FastCall (globals=<optimized out>, nargs=2, args=<optimized out>, co=<optimized out>) at /usr/src/debug/python3-3.6.6-1.fc28.x86_64/Python/ceval.c:4947
#49 fast_function () at /usr/src/debug/python3-3.6.6-1.fc28.x86_64/Python/ceval.c:4947
#50 0x00007ffff79fccc2 in call_function () at /usr/src/debug/python3-3.6.6-1.fc28.x86_64/Python/ceval.c:4851
#51 0x00007ffff7a2d12a in _PyEval_EvalFrameDefault () at /usr/src/debug/python3-3.6.6-1.fc28.x86_64/Python/ceval.c:3328
#52 0x00007ffff79b4d5a in _PyFunction_FastCall (globals=<optimized out>, nargs=1, args=<optimized out>, co=<optimized out>) at /usr/src/debug/python3-3.6.6-1.fc28.x86_64/Python/ceval.c:4947
#53 fast_function () at /usr/src/debug/python3-3.6.6-1.fc28.x86_64/Python/ceval.c:4947
#54 0x00007ffff79fccc2 in call_function () at /usr/src/debug/python3-3.6.6-1.fc28.x86_64/Python/ceval.c:4851
#55 0x00007ffff7a2d12a in _PyEval_EvalFrameDefault () at /usr/src/debug/python3-3.6.6-1.fc28.x86_64/Python/ceval.c:3328
#56 0x00007ffff797e02b in _PyEval_EvalCodeWithName () at /usr/src/debug/python3-3.6.6-1.fc28.x86_64/Python/ceval.c:4159
#57 0x00007ffff797f2e8 in _PyFunction_FastCallDict () at /usr/src/debug/python3-3.6.6-1.fc28.x86_64/Python/ceval.c:5054
#58 0x00007ffff797faae in _PyObject_FastCallDict () at /usr/src/debug/python3-3.6.6-1.fc28.x86_64/Objects/abstract.c:2310
#59 0x00007ffff798b3f0 in _PyObject_Call_Prepend () at /usr/src/debug/python3-3.6.6-1.fc28.x86_64/Objects/abstract.c:2373
#60 0x00007ffff797fe83 in PyObject_Call () at /usr/src/debug/python3-3.6.6-1.fc28.x86_64/Objects/abstract.c:2261
#61 0x00007ffff79f1f86 in slot_tp_init () at /usr/src/debug/python3-3.6.6-1.fc28.x86_64/Objects/typeobject.c:6407
#62 0x00007ffff79ede42 in type_call () at /usr/src/debug/python3-3.6.6-1.fc28.x86_64/Objects/typeobject.c:915
#63 0x00007ffff797f81b in _PyObject_FastCallDict () at /usr/src/debug/python3-3.6.6-1.fc28.x86_64/Objects/abstract.c:2331
#64 0x00007ffff79edd38 in _PyObject_FastCallKeywords () at /usr/src/debug/python3-3.6.6-1.fc28.x86_64/Objects/abstract.c:2482
#65 0x00007ffff79fcd41 in call_function () at /usr/src/debug/python3-3.6.6-1.fc28.x86_64/Python/ceval.c:4854
#66 0x00007ffff7a2d12a in _PyEval_EvalFrameDefault () at /usr/src/debug/python3-3.6.6-1.fc28.x86_64/Python/ceval.c:3328
#67 0x00007ffff79ff058 in _PyEval_EvalCodeWithName (qualname=0x0, name=<optimized out>, closure=0x0, kwdefs=0x0, defcount=0, defs=0x0, kwstep=2, kwcount=<optimized out>, kwargs=<optimized out>, kwnames=<optimized out>, argcount=<optimized out>, args=<optimized out>, locals=<unknown at remote 0x7ffff7f2d288>, globals=<unknown at remote 0x7ffff7f2d288>, _co=<unknown at remote 0x7fffea06fe40>) at /usr/src/debug/python3-3.6.6-1.fc28.x86_64/Python/ceval.c:4180
#68 PyEval_EvalCodeEx () at /usr/src/debug/python3-3.6.6-1.fc28.x86_64/Python/ceval.c:4180
#69 0x00007ffff79fff0b in PyEval_EvalCode (co=co@entry=<unknown at remote 0x7fffea06fe40>, globals=globals@entry=<unknown at remote 0x7ffff7f2d288>, locals=locals@entry=<unknown at remote 0x7ffff7f2d288>) at /usr/src/debug/python3-3.6.6-1.fc28.x86_64/Python/ceval.c:731
#70 0x00007ffff7a997f2 in run_mod () at /usr/src/debug/python3-3.6.6-1.fc28.x86_64/Python/pythonrun.c:1025
#71 0x00007ffff7a9b3ca in PyRun_FileExFlags () at /usr/src/debug/python3-3.6.6-1.fc28.x86_64/Python/pythonrun.c:978
#72 0x00007ffff7a9c128 in PyRun_SimpleFileExFlags () at /usr/src/debug/python3-3.6.6-1.fc28.x86_64/Python/pythonrun.c:420
#73 0x00007ffff7a9c2e9 in PyRun_AnyFileExFlags () at /usr/src/debug/python3-3.6.6-1.fc28.x86_64/Python/pythonrun.c:81
#74 0x00007ffff7a9d1fe in run_file (p_cf=<error reading variable: Dwarf Error: could not find partial DIE containing offset 0x316 [in module /usr/lib/debug/usr/bin/python3.6-3.6.6-1.fc28.x86_64.debug]>, filename=<optimized out>, fp=0x555555809820) at /usr/src/debug/python3-3.6.6-1.fc28.x86_64/Modules/main.c:344
#75 Py_Main () at /usr/src/debug/python3-3.6.6-1.fc28.x86_64/Modules/main.c:814
```

Please let me know if there is anything else I can do to help.

**Comment by drebbe-intrepid** [comment]
@cottsay 

Sorry I missed this report, slipped through the cracks somehow...

I'll try to reproduce this on my end.

**Comment by drebbe-intrepid** [comment]
@cottsay Issue should be resolved now.

For some reason I decided it would be sane to memset a const char array and its been working for the most part but is undefined behavior. Below is a copy of the stack trace.


> Using host libthread_db library "/lib64/libthread_db.so.1".
> Python 3.6.7 (default, Nov 23 2018, 12:11:28) 
> [GCC 8.2.1 20181105 (Red Hat 8.2.1-5)] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import ics
> >>> ics.find_devices()
> 
> Program received signal SIGSEGV, Segmentation fault.
> arg_parse (args=args@entry=0x7fffe9a590cb "|Oi:", func=func@entry=0x7fffe9a5a980 <meth_find_devices(_object*, _object*, _object*)::__FUNCTION__> "meth_find_devices") at src/methods.cpp:47
> 47	    memset(buffer, '\0', sizeof(buffer)/sizeof(buffer[0]));
> (gdb) bt
> #0  arg_parse (args=args@entry=0x7fffe9a590cb "|Oi:", func=func@entry=0x7fffe9a5a980 <meth_find_devices(_object*, _object*, _object*)::__FUNCTION__> "meth_find_devices")
>     at src/methods.cpp:47
> #1  0x00007fffe9a3eaef in meth_find_devices(_object*, _object*, _object*) () at src/methods.cpp:168
> #2  0x00007ffff797ca83 in _PyCFunction_FastCallDict () at /usr/src/debug/python3-3.6.7-2.fc28.x86_64/Objects/methodobject.c:231
> #3  0x00007ffff798e6fa in _PyCFunction_FastCallKeywords () at /usr/src/debug/python3-3.6.7-2.fc28.x86_64/Objects/methodobject.c:275
> #4  0x00007ffff79f0b0d in call_function () at /usr/src/debug/python3-3.6.7-2.fc28.x86_64/Python/ceval.c:4837
> #5  0x00007ffff7a3323a in _PyEval_EvalFrameDefault () at /usr/src/debug/python3-3.6.7-2.fc28.x86_64/Python/ceval.c:3335
> #6  0x00007ffff7a1a657 in _PyEval_EvalCodeWithName (qualname=0x0, name=<optimized out>, closure=0x0, kwdefs=0x0, defcount=0, defs=0x0, kwstep=2, kwcount=<optimized out>, 
>     kwargs=<optimized out>, kwnames=<optimized out>, argcount=<optimized out>, args=<optimized out>, locals=<unknown at remote 0x7ffff7f54288>, globals=<unknown at remote 0x7ffff7f54288>, 
>     _co=<unknown at remote 0x7ffff7ecfe40>) at /usr/src/debug/python3-3.6.7-2.fc28.x86_64/Python/ceval.c:4187
> #7  PyEval_EvalCodeEx () at /usr/src/debug/python3-3.6.7-2.fc28.x86_64/Python/ceval.c:4187
> #8  0x00007ffff7a1b54b in PyEval_EvalCode (co=co@entry=<unknown at remote 0x7ffff7ecfe40>, globals=globals@entry=<unknown at remote 0x7ffff7f54288>, 
>     locals=locals@entry=<unknown at remote 0x7ffff7f54288>) at /usr/src/debug/python3-3.6.7-2.fc28.x86_64/Python/ceval.c:731
> #9  0x00007ffff7a99fd2 in run_mod () at /usr/src/debug/python3-3.6.7-2.fc28.x86_64/Python/pythonrun.c:1025
> #10 0x00007ffff7946f00 in PyRun_InteractiveOneObjectEx (fp=fp@entry=0x7ffff6ebaa00 <_IO_2_1_stdin_>, filename=filename@entry=<unknown at remote 0x7ffff7f0fbc8>, 
>     flags=flags@entry=0x7fffffffd51c) at /usr/src/debug/python3-3.6.7-2.fc28.x86_64/Python/pythonrun.c:246
> #11 0x00007ffff7949e8d in PyRun_InteractiveLoopFlags (fp=fp@entry=0x7ffff6ebaa00 <_IO_2_1_stdin_>, filename_str=filename_str@entry=0x7ffff7a9de03 "<stdin>", 
>     flags=flags@entry=0x7fffffffd51c) at /usr/src/debug/python3-3.6.7-2.fc28.x86_64/Python/pythonrun.c:114
> #12 0x00007ffff7949f2a in PyRun_AnyFileExFlags (fp=0x7ffff6ebaa00 <_IO_2_1_stdin_>, 
>     fp@entry=<error reading variable: Dwarf Error: could not find partial DIE containing offset 0x316 [in module /usr/lib/debug/usr/bin/python3.6-3.6.7-2.fc28.x86_64.debug]>, 
>     filename=0x7ffff7a9de03 "<stdin>", closeit=0, flags=flags@entry=0x7fffffffd51c) at /usr/src/debug/python3-3.6.7-2.fc28.x86_64/Python/pythonrun.c:75
> #13 0x00007ffff7a9d212 in run_file (p_cf=0x7fffffffd51c, filename=<optimized out>, fp=0x7ffff6ebaa00 <_IO_2_1_stdin_>) at /usr/src/debug/python3-3.6.7-2.fc28.x86_64/Modules/main.c:344
> #14 Py_Main () at /usr/src/debug/python3-3.6.7-2.fc28.x86_64/Modules/main.c:814

**Comment by cottsay** [comment]
I confirmed your fix. Thanks, @drebbe-intrepid!
