### ISSUE TITLE
RuntimeError when using many of the ICS functions

### ISSUE THREAD

**Issue by KungFuCharlie** [intrepidcs/python_ics#25]
I am using Python 3.7.0 with the latest python-ics files. I am able to call find_devices() and get a valid ics.NeoDevice object for the neoVI FIRE2 and print variables such as device.Name and device.SerialNumber.

```
Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:06:47) [MSC v.1914 32 bit (Intel)] on win32
import ics
dl = ics.find_devices()
dl
(<ics.NeoDevice neoVI FIRE2 CY4304>,)
```

However, whenever I try to call additional API functions I get RuntimeError exceptions.

```
d = dl[0]

ics.get_device_status(d)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
ics.RuntimeError: Error: get_device_status(): Failed to Retrieve address of function 'icsneoGetDeviceStatus': Windows Error #127 for library 'icsneo40.dll'

ics.open_device(d)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
ics.RuntimeError: Error: open_device(): Failed to open device (neoVI FIRE2 782891572 - )
```

The DLL file does appear to be found properly.

```
ics.get_dll_version()
802

ics.get_library_path()
'C:\\windows\\SYSTEM32\\icsneo40.dll'

ics.get_dll_firmware_info(d)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
ics.RuntimeError: Error: get_dll_firmware_info(): icsneoGetDLLFirmwareInfo() Failed
```

**Comment by KungFuCharlie** [comment]
This also appears to be a problem using the device in Vehicle Spy 3 so I no longer think it is a python-ics problem.
