### ISSUE TITLE
I can not open the device with RuntimeError raised

### ISSUE THREAD

**Issue by YelaShady** [intrepidcs/python_ics#45]
Hi
    I am glad that I find such a usefull python lib for VehicleSpy. But when I run the 'open_device_example.py' it fails withe RuntimeError raised:
Traceback (most recent call last):
  File "D:\spy.py", line 37, in <module>
    device = open_device(i)
  File "D:\spy.py", line 26, in open_device
    device = ics.open_device()
ics.RuntimeError: Error: open_device(): Failed to open device (neoVI FIRE2 782803629 - )
I think I can connect the device sucessfully because it shows that:
Found 1 connected device(s)...
Opening Device neoVI FIRE2 CY2759 (Open Client handles: 0)...
I can not get any hints for  this error, so can you help me with this issue?

**Comment by YelaShady** [comment]
With another device , This issue is solved.
