### ISSUE TITLE
Linux Used libicsneo/libicsneolegacy transmit_messages got "ics.RuntimeError: Error: transmit_messages(): icsneoTxMessages() Failed"

### ISSUE THREAD

**Issue by eismog** [intrepidcs/python_ics#83]
The device can be connected  and some can signal can be received,
but can't send bellow can msg.

```

#commit a5b27a15b016db421593fde4bdbcc2a8e2bc5da4
ics.override_library_name("/home/xxx/tool/libicsneo/libicsneolegacy.so")

Message = collections.namedtuple('Message',
                                 'arbid, data, network, extended, rate')

xxx = \
    Message('1C', "000000000000000000040000000000000000000000000000000000", ics.NETID_MSCAN, False, 0.12)

msg = convert_message(xxx)
ics.transmit_messages(device, msg)`
```

### log
```
/usr/bin/python3.8 /home/xxx/pycharm/python_ics_test/main.py
Found 1 connected device(s)...
Opening Device...
Opened Device neoVI FIRE2 CY5495.
Traceback (most recent call last):
  File "/home/xxx/pycharm/python_ics_test/main.py", line 110, in <module>
    transmit_can(dev)
  File "/home/xxx/pycharm/python_ics_test/main.py", line 70, in transmit_can
    ics.transmit_messages(device, msg)
ics.RuntimeError: Error: transmit_messages(): icsneoTxMessages() Failed

Process finished with exit code 1

```

**Comment by eismog** [comment]
This msg is can-FD. my error use case. so close it.
